# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mysqlsrv:
    image: mysql:latest
    container_name: my-sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "PService"
    ports:
      - "3306:3306"
    volumes:
      - /Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
      - ./PService.Infrastructure/init:/docker-entrypoint-initdb.d
    networks:
      - mysql-compose-network
networks: 
  mysql-compose-network:
    driver: bridge
